### ISSUE TITLE
clangCore is not installed

### ISSUE THREAD

**Issue by jdahm** [MeteoSwiss-APN/yoda#15]
The version of clang installed on Ubuntu 18.04 doesn't have `clangCore`, but the FindClang.cmake looks for it and fails on my system. All others seem to exist, however. Is my installation broken or is the `FindClang.cmake` file out of date?

**Comment by twicki** [comment]
I cant test this locally but our docker-builds find clang:
https://cloud.docker.com/u/gtclang/repository/docker/gtclang/dawn/builds/7ab46085-beed-4daf-a995-646c1d0f7544

Maybe @havogt  can doublecheck?

**Comment by havogt** [comment]
hmm no idea...

**Comment by jdahm** [comment]
I'm not certain this is still an issue. Closing for now.
